# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shreyansh/Documents/dbsproject/ds-sql

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shreyansh/Documents/dbsproject/ds-sql

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shreyansh/Documents/dbsproject/ds-sql/CMakeFiles /home/shreyansh/Documents/dbsproject/ds-sql/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shreyansh/Documents/dbsproject/ds-sql/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ds-sql

# Build rule for target.
ds-sql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ds-sql
.PHONY : ds-sql

# fast build rule for target.
ds-sql/fast:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/build
.PHONY : ds-sql/fast

src/Attribute.o: src/Attribute.cpp.o

.PHONY : src/Attribute.o

# target to build an object file
src/Attribute.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Attribute.cpp.o
.PHONY : src/Attribute.cpp.o

src/Attribute.i: src/Attribute.cpp.i

.PHONY : src/Attribute.i

# target to preprocess a source file
src/Attribute.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Attribute.cpp.i
.PHONY : src/Attribute.cpp.i

src/Attribute.s: src/Attribute.cpp.s

.PHONY : src/Attribute.s

# target to generate assembly for a file
src/Attribute.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Attribute.cpp.s
.PHONY : src/Attribute.cpp.s

src/Constraint.o: src/Constraint.cpp.o

.PHONY : src/Constraint.o

# target to build an object file
src/Constraint.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Constraint.cpp.o
.PHONY : src/Constraint.cpp.o

src/Constraint.i: src/Constraint.cpp.i

.PHONY : src/Constraint.i

# target to preprocess a source file
src/Constraint.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Constraint.cpp.i
.PHONY : src/Constraint.cpp.i

src/Constraint.s: src/Constraint.cpp.s

.PHONY : src/Constraint.s

# target to generate assembly for a file
src/Constraint.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Constraint.cpp.s
.PHONY : src/Constraint.cpp.s

src/Lexer.o: src/Lexer.cpp.o

.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i

.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s

.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/Table.o: src/Table.cpp.o

.PHONY : src/Table.o

# target to build an object file
src/Table.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Table.cpp.o
.PHONY : src/Table.cpp.o

src/Table.i: src/Table.cpp.i

.PHONY : src/Table.i

# target to preprocess a source file
src/Table.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Table.cpp.i
.PHONY : src/Table.cpp.i

src/Table.s: src/Table.cpp.s

.PHONY : src/Table.s

# target to generate assembly for a file
src/Table.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Table.cpp.s
.PHONY : src/Table.cpp.s

src/Type.o: src/Type.cpp.o

.PHONY : src/Type.o

# target to build an object file
src/Type.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Type.cpp.o
.PHONY : src/Type.cpp.o

src/Type.i: src/Type.cpp.i

.PHONY : src/Type.i

# target to preprocess a source file
src/Type.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Type.cpp.i
.PHONY : src/Type.cpp.i

src/Type.s: src/Type.cpp.s

.PHONY : src/Type.s

# target to generate assembly for a file
src/Type.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/Type.cpp.s
.PHONY : src/Type.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/repl.o: src/repl.cpp.o

.PHONY : src/repl.o

# target to build an object file
src/repl.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/repl.cpp.o
.PHONY : src/repl.cpp.o

src/repl.i: src/repl.cpp.i

.PHONY : src/repl.i

# target to preprocess a source file
src/repl.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/repl.cpp.i
.PHONY : src/repl.cpp.i

src/repl.s: src/repl.cpp.s

.PHONY : src/repl.s

# target to generate assembly for a file
src/repl.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/repl.cpp.s
.PHONY : src/repl.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/ds-sql.dir/build.make CMakeFiles/ds-sql.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ds-sql"
	@echo "... src/Attribute.o"
	@echo "... src/Attribute.i"
	@echo "... src/Attribute.s"
	@echo "... src/Constraint.o"
	@echo "... src/Constraint.i"
	@echo "... src/Constraint.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/Table.o"
	@echo "... src/Table.i"
	@echo "... src/Table.s"
	@echo "... src/Type.o"
	@echo "... src/Type.i"
	@echo "... src/Type.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/repl.o"
	@echo "... src/repl.i"
	@echo "... src/repl.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

